services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: root
    ports:
      - 8082:80
    volumes:
      - /data:/srv
      - /data/config/management/filebrowser:/database
      - /minecraft:/srv/minecraft-pool
