services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: filebrowser
    restart: unless-stopped
    user: root
    ports:
      - 8082:80
    environment:
      - FILEBROWSER_DATABASE=${FILEBROWSER_DATABASE}
    volumes:
      - /data:/srv
      - /data/config/management/filebrowser:/database
      - /minecraft:/srv/minecraft-pool
